# -*- coding: utf-8 -*-
"""robfurtloc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qRbRFFoJTyBmaaPcir6Wj2ByJC2-BnDs

# Importação das bibliotecas necessárias
"""

import pandas as pd
import matplotlib.pyplot as plt
import datetime
import numpy as np
import datetime
from datetime import datetime
from datetime import time
import openpyxl
"""# Importação da base de dados(retirada da SSP-SP, período 2025-jan-abr)"""

df_sp = pd.read_excel("VeiculosSubtraidos_2025.xlsx")

#np.sort(df_sp.CIDADE.unique())
#defining filters for the most relevant columns/ definindo filtros das colunas mais relevantes
filtro_colunas = ['CIDADE','BAIRRO','LOGRADOURO','NUMERO_LOGRADOURO','NUM_BO','DATA_OCORRENCIA_BO','HORA_OCORRENCIA','DESCR_OCORRENCIA_VEICULO','DESCR_TIPO_VEICULO', 'DESCR_MARCA_VEICULO','ANO_MODELO','PLACA_VEICULO','DESC_COR_VEICULO']
#filtering for cities that are part of 33ºBPM/M // Filtrando por cidades que compõe o 33ºBPM/M
filtro_cidades = ['COTIA','CARAPICUIBA','VARGEM GRANDE PAULISTA']
#filtering for 3º and 4º companies / filtrando pela 3ª e 4ª cia
filtro_34cia= ['COTIA','VARGEM GRANDE PAULISTA']

#applying filters and creating the DataFrame containing all the cities within 33ºBPM/M
df33m = df_sp.query('@filtro_cidades in CIDADE').copy()
#removing every row where the vehicle plate is null, since without the plate, there will be many issues when merging
df33m.dropna(subset=['PLACA_VEICULO'], inplace=True)
df33m = df33m[filtro_colunas]
#creating subsets
df33m_r = df33m.query('"Roubado" in DESCR_OCORRENCIA_VEICULO')
df33m_f = df33m.query('"Furtado" in DESCR_OCORRENCIA_VEICULO')
df33m_rf = df33m.query('["Furtado","Roubado"] in DESCR_OCORRENCIA_VEICULO')
df_loc = df_sp.query('"Localizado / Entregue" in DESCR_OCORRENCIA_VEICULO')

"""# Mesclando as bases de dados de furto e roubo com localização"""

#merging the robbed and stolen dataframes with the localized, using plate as reference

df33m_mesc_r = df33m_r.merge(df_loc[['CIDADE','BAIRRO','PLACA_VEICULO','LOGRADOURO','NUMERO_LOGRADOURO']], on='PLACA_VEICULO',  suffixes=('_robfur','_loc') )
df33m_mesc_f = df33m_f.merge(df_loc[['CIDADE','BAIRRO','PLACA_VEICULO','LOGRADOURO','NUMERO_LOGRADOURO']], on='PLACA_VEICULO',  suffixes=('_robfur','_loc') )
df33m_mesc_rf = df33m_rf.merge(df_loc[['CIDADE','BAIRRO','PLACA_VEICULO','LOGRADOURO','NUMERO_LOGRADOURO']], on='PLACA_VEICULO',  suffixes=('_robfur','_loc') )
df33m_mesc_rf.drop_duplicates(inplace=True)
df33m_mesc_r.drop_duplicates(inplace=True)
df33m_mesc_f.drop_duplicates(inplace=True)

#df33m_mesc.groupby(['BAIRRO'])['LOGRADOURO_loc'].value_counts().sort_values(ascending=False)
#df33m_mesc['LOGRADOURO_loc'].value_counts()
df_final=df33m_mesc_rf.sort_values(by='LOGRADOURO_loc').head(50)
